SOLUTION_PREFIX = "ybor"
SOLUTION_NAME = "agent"
SEGMENTS = ["all-segments"]
PINECONE_API_KEY = ""
PINECONE_ENV = "us-east-1-aws"
PINECONE_INDEX_METRIC = "cosine"
EMBEDDING_MODEL_DIMENSIONS = 1536
OPENAI_API_KEY = ""
PINECONE_API_KEY = ""

